<?php
	
	function foss_upload_menu(){
	$items['upload-files'] = array(
		'title' => 'Upload Document',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_files_form'),
		'access callback' => TRUE,
	);
	$items['admin/settings/documents'] = array(
		'title' => 'FOSS Document Settings',
		'description' => 'FOSS Document URL Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('foss_doc_settings_form'),
		'access arguments' => array('administer foss document setting'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['download'] = array(
		'title' => 'Download Documents',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('download_form'),
		'access callback' => TRUE,
		'file' => 'download.inc',
	);
	$items['filter/get_doc_type'] = array(
		'page callback' => 'filter',
		'access callback' => TRUE,
		'file' => 'download.inc',
	);
	return $items;
	}
	
	function foss_upload_perm() {
		return array('administer foss document setting');
	}
	
	function upload_files_form($form_state)
	{
		$path = drupal_get_path('module', 'foss_upload');
		drupal_add_js($path.'/filter.js');
		$form['foss_category'] = array(
			'#type' => 'select',
			'#title' => t('FOSS Category Name'),
			'#required' => TRUE,
			'#options' => array("Scilab" => "Scilab","Python" => "Python","Oscad" => "Oscad",'OpenFOAM' => "OpenFOAM","OR-Tools" => "OR-Tools"),
		);
		$form['files'] = array(
			'#type' => 'select',
			'#title' => t('File to be Uploaded'),
			'#required' => TRUE,
			'#options' => array("All" => "All","Brochures" => "Brochures","Posters" => "Posters",'Logo' => "Logos","Installer" => "Installer"),
		);
		$form['file_name'] = array(
			'#type' => 'textfield',
			'#title' => t('File name'),
			'#required' => TRUE,
			'#description' => "Please enter file name.",
		);
		$form['file-upload'] = array(
			'#type' => 'file',
			'#title' => t('Upload File'),
			'#attributes' => array('class' => 'upeng_video'),
			'#prefix' => '<div class="stupload-form-video">',
			'#suffix' => '</div>'
		);		
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Submit'),
			'#prefix' => "<div style='clear:both;'>",
			'#suffix' => "</div>"
		);

		return $form;
	}
	
	function upload_files_form_submit($form,&$form_state)
	{
		global $user;

		$path = variable_get('doc_foss', '');
		$temp_path = "sites/default/files/documents/";

		$foo = ucwords($form_state['values']['file_name']);
		$foo_temp = str_replace (" ", "-", $foo);

		$file_ext = substr($_FILES['files']['name']['file-upload'], strripos($_FILES['files']['name']['file-upload'], '.'));
		$file_name = $form_state['values']['foss_category']."-".$form_state['values']['files']."-".$foo_temp.$file_ext;

		$path = $path.$file_name;
		$temp_path = $temp_path.$file_name;

		if(move_uploaded_file($_FILES['files']['tmp_name']['file-upload'], $path)){
			$query = "INSERT INTO `foss_documents` (`foss`, `doc_type`, `doc_url`, `user_id`, `upload_time`) VALUES ('".$form_state['values']['foss_category']."','".$form_state['values']['files']."', '".$temp_path."','".$user->uid."', CURRENT_TIMESTAMP)";
			db_query($query);
			drupal_set_message("File uploaded Successfully!!");
		}
	}
	
	function foss_doc_settings_form($form_state)
	{
		$form['foss_document'] = array(
			'#type' => 'textfield',
			'#title' => t('URL'),
			'#description' => t('Please specify URL for storing the Brochures,Installer,Logos and etc.'),
			'#size' => 100,
			'#maxlength' => 255,
			'#required' => TRUE,
			'#default_value' => variable_get('doc_foss', ''),
		);
		$form['submit'] = array(
			'#type' => 'submit',
			'#value' => t('Submit')
		);

		return $form;
	}
	
	function foss_doc_settings_form_submit($form, &$form_state)
	{
		variable_set('doc_foss', $form_state['values']['foss_document']);
		drupal_set_message(t('Settings updated'), 'status');
	}
	
	
?>
